name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [win64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.4.1
        with:
          name: Catan.exe
          preset: ${{ matrix.platform }}
          debugMode: "false"
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Catan-${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
