name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [Windows Desktop]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.4.1
        with:
          name: example
          preset: ${{ matrix.platform }}
          debugMode: "false"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
